language: android
android:
  components:
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - '.+'

jdk: oraclejdk8

script: ./gradlew testDebug
